from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(390, 258)
        MainWindow.setFixedSize(390, 258)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(10, 10, 441, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(250, 100, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        self.equals = QtWidgets.QPushButton(self.centralwidget)
        self.equals.setGeometry(QtCore.QRect(250, 140, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.equals.setFont(font)
        self.equals.setObjectName("equals")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(320, 180, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.plus.setFont(font)
        self.plus.setObjectName("plus")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(320, 220, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.minus.setFont(font)
        self.minus.setObjectName("minus")
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(320, 140, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.multiply.setFont(font)
        self.multiply.setObjectName("multiply")
        self.division = QtWidgets.QPushButton(self.centralwidget)
        self.division.setGeometry(QtCore.QRect(320, 100, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.division.setFont(font)
        self.division.setObjectName("division")
        self.int_7 = QtWidgets.QPushButton(self.centralwidget)
        self.int_7.setGeometry(QtCore.QRect(0, 100, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.int_7.setFont(font)
        self.int_7.setObjectName("int_7")
        self.int_8 = QtWidgets.QPushButton(self.centralwidget)
        self.int_8.setGeometry(QtCore.QRect(70, 100, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.int_8.setFont(font)
        self.int_8.setObjectName("int_8")
        self.int_9 = QtWidgets.QPushButton(self.centralwidget)
        self.int_9.setGeometry(QtCore.QRect(140, 100, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.int_9.setFont(font)
        self.int_9.setObjectName("int_9")
        self.int_4 = QtWidgets.QPushButton(self.centralwidget)
        self.int_4.setGeometry(QtCore.QRect(0, 140, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.int_4.setFont(font)
        self.int_4.setObjectName("int_4")
        self.int_5 = QtWidgets.QPushButton(self.centralwidget)
        self.int_5.setGeometry(QtCore.QRect(70, 140, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.int_5.setFont(font)
        self.int_5.setObjectName("int_5")
        self.int_6 = QtWidgets.QPushButton(self.centralwidget)
        self.int_6.setGeometry(QtCore.QRect(140, 140, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.int_6.setFont(font)
        self.int_6.setObjectName("int_6")
        self.int_1 = QtWidgets.QPushButton(self.centralwidget)
        self.int_1.setGeometry(QtCore.QRect(0, 180, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.int_1.setFont(font)
        self.int_1.setObjectName("int_1")
        self.int_2 = QtWidgets.QPushButton(self.centralwidget)
        self.int_2.setGeometry(QtCore.QRect(70, 180, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.int_2.setFont(font)
        self.int_2.setObjectName("int_2")
        self.int_3 = QtWidgets.QPushButton(self.centralwidget)
        self.int_3.setGeometry(QtCore.QRect(140, 180, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.int_3.setFont(font)
        self.int_3.setObjectName("int_3")
        self.int_0 = QtWidgets.QPushButton(self.centralwidget)
        self.int_0.setGeometry(QtCore.QRect(70, 220, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.int_0.setFont(font)
        self.int_0.setObjectName("int_0")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.minus.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ST0PCHA\'s Calculator"))
        self.result.setText(_translate("MainWindow", ""))
        self.clear.setText(_translate("MainWindow", "C"))
        self.equals.setText(_translate("MainWindow", "="))
        self.plus.setText(_translate("MainWindow", "+"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.multiply.setText(_translate("MainWindow", "×"))
        self.division.setText(_translate("MainWindow", "÷"))
        self.int_7.setText(_translate("MainWindow", "7"))
        self.int_8.setText(_translate("MainWindow", "8"))
        self.int_9.setText(_translate("MainWindow", "9"))
        self.int_4.setText(_translate("MainWindow", "4"))
        self.int_5.setText(_translate("MainWindow", "5"))
        self.int_6.setText(_translate("MainWindow", "6"))
        self.int_1.setText(_translate("MainWindow", "1"))
        self.int_2.setText(_translate("MainWindow", "2"))
        self.int_3.setText(_translate("MainWindow", "3"))
        self.int_0.setText(_translate("MainWindow", "0"))

        for _int in range(0, 10):
            getattr(self, 'int_%s' % _int).pressed.connect(lambda i=_int: self.write(i))

        self.minus.clicked.connect(lambda: self.write("-"))
        self.plus.clicked.connect(lambda: self.write("+"))
        self.multiply.clicked.connect(lambda: self.write("*"))
        self.division.clicked.connect(lambda: self.write("/"))

        self.equals.clicked.connect(lambda: self.get_result())

        self.clear.clicked.connect(lambda: self.clear_result())

    def clear_result(self):
        self.result.setText("")

    def write(self, arg):
        self.result.setText(self.result.text() + str(arg))

    def get_result(self):
        if self.result.text() == "":
            self.clear_result()

        result = eval(self.result.text())
        self.result.setText(str(result))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
